import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Check, Copy, Instagram, Linkedin, Link as LinkIcon, Mail, Phone, QrCode, Share2, Sparkles, X } from 'lucide-react';
import './style.css';

const API_BASE = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const api = async (url, options={}) => { const response=await fetch(`${API_BASE}${url}`,{credentials:'same-origin',...options,headers:options.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options.headers}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||`Request failed (${response.status})`); return data; };
const initials = name => name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase();
const toastCopy = async (value,setNotice) => { try {await navigator.clipboard.writeText(value);setNotice('Copied to clipboard');}catch{setNotice('Copy unavailable in this browser');} setTimeout(()=>setNotice(''),2800); };

function Logo() {return <a className="brand" href="/" aria-label="IEEE VJEC home"><img className="brand-logo" src="/ieee-vjec-logo.png" alt=""/><span>IEEE <strong>VJEC</strong></span></a>}
function Button({children,className='',...props}) {return <button className={`btn ${className}`} {...props}>{children}</button>}
function Avatar({profile,className=''}) {return profile.photo?<img className={`avatar ${className}`} src={profile.photo?.startsWith('/') && API_BASE ? `${API_BASE}${profile.photo}` : profile.photo} alt={profile.name} />:<div className={`avatar avatar-fallback ${className}`}>{initials(profile.name)}</div>}

function App(){const path=window.location.pathname;return <PublicProfile slug={path.startsWith('/profile/')?decodeURIComponent(path.slice(9)):'arjun'}/>;}
function PublicProfile({slug}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[qrOpen,setQrOpen]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{api(`/api/profiles/${encodeURIComponent(slug)}`).then(setData).catch(e=>setError(e.message));},[slug]);
 const p=data?.profile,url=data?.url;
 const downloadVcard=()=>{const esc=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const v=`BEGIN:VCARD\r\nVERSION:3.0\r\nFN:${esc(p.name)}\r\nTITLE:${esc(p.designation)}\r\nORG:${esc(p.organization)}\r\nEMAIL:${esc(p.email)}\r\nTEL:${esc(p.phone)}\r\nURL:${url}\r\nEND:VCARD\r\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([v],{type:'text/vcard'}));a.download=`${p.slug}.vcf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 const share=async()=>{if(navigator.share){try{await navigator.share({title:`${p.name} | ${p.organization}`,url});}catch{}}else toastCopy(url,setNotice)};
 return <div className="site public-site"><div className="top-strip"><span>THE PEOPLE BEHIND THE MOMENT</span><span className="strip-right">SCAN • CONNECT • GO</span></div><header className="site-header"><Logo/><div className="header-right"><span className="live-pill"><i/>DIGITAL IDENTITY</span></div></header>
 {error?<main className="not-found"><div className="error-num">404<span>.</span></div><h1>Profile not found.</h1><p>This profile may be inactive or the link has changed.</p><a className="btn btn-yellow" href="/">View demo profile <ArrowRight size={17}/></a></main>:!p?<main className="loading">LOADING PROFILE<span className="blink">_</span></main>:<>
 <main className="public-main"><div className="page-index"><span>01 / COORDINATOR PROFILE</span><span>OFFICIAL DIGITAL ID ↗</span></div><div className="profile-grid"><section className="identity-card"><div className="id-card-top"><span><span className="tiny-square"/> OFFICIAL COORDINATOR</span><span>NO. {String(p.id).padStart(4,'0')}</span></div><div className="photo-wrap"><Avatar profile={p}/></div><div className="identity-bottom"><span className="eyebrow">MEET YOUR COORDINATOR</span><h1>{p.name}<span>.</span></h1><div className="role-line"><span>{p.designation}</span><span className="role-arrow">↗</span></div><div className="id-meta"><div className="team-role-meta"><small>TEAM ROLE</small><strong>{p.team_role||'—'}</strong></div>{p.society&&<div className="society-meta"><small>SOCIETY</small><strong>{p.society}</strong></div>}{p.organization&&<div className="organization-meta"><small>ORGANIZATION</small><strong>{p.organization}</strong></div>}{p.department&&<div className="academic-meta"><small>ACADEMIC DEPARTMENT</small><strong>{p.department}</strong></div>}</div></div></section>
 <section className="info-column"><div className="intro-block"><div className="intro-tag"><Sparkles size={15}/> MORE THAN A NAME ON AN ID</div><h2>Hey there<span className="wave">✳</span><br/>let’s connect.</h2><p>{p.bio||`I'm ${p.name}, a coordinator at ${p.organization||'IEEE VJEC'}. Let's connect!`}</p><div className="scribble">GOOD PEOPLE. GREAT IDEAS. REAL CONNECTIONS.</div></div>
 <div className="action-grid"><Button className="btn-yellow action-primary" onClick={downloadVcard}><ArrowDownToLine size={21}/> Save contact <ArrowUpRight size={18}/></Button><Button className="btn-blue" onClick={share}><Share2 size={21}/> Share profile <ArrowUpRight size={18}/></Button><Button className="btn-white" onClick={()=>setQrOpen(true)}><QrCode size={21}/> Show QR code <ArrowUpRight size={18}/></Button><Button className="btn-white" onClick={()=>toastCopy(url,setNotice)}><Copy size={21}/> Copy profile URL <ArrowUpRight size={18}/></Button></div>
 {(p.instagram||p.linkedin||p.email||p.phone||p.links.length>0)&&<div className="connect-block"><div className="section-heading"><span>WAYS TO REACH ME</span><span>↘</span></div><div className="social-grid">{p.instagram&&<a className="social-link" href={p.instagram} target="_blank" rel="noreferrer"><Instagram size={23}/><span>Instagram</span><ArrowUpRight size={18}/></a>}{p.linkedin&&<a className="social-link" href={p.linkedin} target="_blank" rel="noreferrer"><Linkedin size={23}/><span>LinkedIn</span><ArrowUpRight size={18}/></a>}{p.email&&<a className="social-link" href={`mailto:${p.email}`}><Mail size={23}/><span>Email me</span><ArrowUpRight size={18}/></a>}{p.phone&&<a className="social-link" href={`tel:${p.phone.replace(/[^+\d]/g,'')}`}><Phone size={23}/><span>Call me</span><ArrowUpRight size={18}/></a>}{p.links.map((link,i)=><a key={i} className="social-link" href={link.url} target="_blank" rel="noreferrer"><LinkIcon size={23}/><span>{link.label}</span><ArrowUpRight size={18}/></a>)}</div></div>}</section></div><div className="profile-foot"><span>MADE TO BE SCANNED. BUILT TO CONNECT.</span><span>↗ IEEE VJEC / {new Date().getFullYear()}</span></div></main></>}
 <footer className="site-footer"><Logo/><span>PEOPLE MAKE THE EVENT.</span><span>© {new Date().getFullYear()} IEEE VJEC</span></footer>{notice&&<div className="toast"><Check size={16}/>{notice}</div>}{qrOpen&&p&&<div className="modal-overlay" onMouseDown={()=>setQrOpen(false)}><div className="qr-dialog" onMouseDown={e=>e.stopPropagation()}><button className="icon-button dialog-close" onClick={()=>setQrOpen(false)} aria-label="Close"><X/></button><div className="eyebrow">SCAN TO CONNECT / {p.name}</div><h2>{p.name}<span>.</span></h2><div className="qr-frame"><img src={`${API_BASE}/api/profiles/${encodeURIComponent(p.slug)}/qr`} alt={`QR code for ${p.name}`}/></div><p>Point your camera here to open this profile.</p><Button className="btn-yellow" onClick={()=>toastCopy(url,setNotice)}><Copy size={18}/> Copy URL</Button></div></div>}</div>;
}


createRoot(document.getElementById('root')).render(<App/>);
